<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

     <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
   <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
        <script type="text/javascript" src="/mksys/Public/syspkg/layer/layer.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
 input
      {
        outline: none;
      }
      select
        {
                   outline: none;
        }
        .home
        {
            
            width: 121px;
            height: 35px;
            line-height: 35px;
            color: rgba(16, 16, 16, 1);
            font-size: 24px;
            text-align: center;
            font-family: Roboto;

        }
         .hr0
        {
           position: relative;
            top: -5px;
            
            height: 12px;

        }
        table 
        {
            width: 80%;

        }
        table,th,td
        {
             border:3px solid;
            border-color: #A6A6A6 ;
             text-align: center;
        }

        tr.hh2 th
        {

             padding: 5px;
            color: #B8B8B8 ;
            border-color: #A6A6A6;
            width: 120px;
        }
        tr.hh3 td
        {

             padding: 5px;
            width: 120px;
        }
        th td
        {
            width: 120px;
        }
        table
        {
            table-layout:fixed; word-break: break-all; word-wrap: break-word;
        }
    </style>
  <script type="text/javascript">
   $(document).ready(function(){

var pageId = '<?php echo ($page); ?>';
//页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：
if(pageId=='page7')
{
    
    $("#m5").css("background-color","#363536");
    $("#d5").css("display","inline");
}


$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'100px'
    },"fast")}else if(heit=="100px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
<script>

$(document).ready(function () {
       $("#yin").click(function () {
           $("#yin").toggleClass("glyphicon-eye-close");
           var va=document.getElementById("psd");

           if(va.type=="password") {
               va.type='text';

           }else {

               va.type='password';
           }

       });

       $("#upload").click(function(){
          // $(location).prop('href',"<?php echo U('Home/updatePhoto');?>");
          document.getElementById("btn-file").click();
            $("#photoupload").ajaxSubmit({
              url : "<?php echo U('Home/updatePhoto');?>",
              type : "post",
              enctype : "multipart/form-data",
              dataType:'text',
              success : function(data){
                if(data=='fail'){
                    alert('更新数据库失败');
                }else if(data=='uploadfail'){
                     alert('文件上传失败');
                }else{
                    $("img#photo2").attr("src", "/MKSYS"+data);
                    $("img#photo1").attr("src", "/MKSYS"+data);
                    window.location.reload();
                }
               
              }
            });  
       });
       $("#download").click(function(){
           
           $.post("<?php echo U('Home/downloadPhoto');?>",
            function(data){
             var d = data.split(" ");
             // 改变a标签中属性值
             $("#adownload").attr("href","/MKSYS"+d[0]);
             $("#adownload").attr("download",d[1]);
             // 模拟点击事件，触发下载事件
             document.getElementById("adownload").click();
            }
            );
        
       });
   });
function psdconfirm() {
    var psd=document.getElementById("psd").value;
    var zmnumReg=/^[0-9a-zA-Z]*$/;
    if(psd!=""&&!zmnumReg.test(psd)){
       layer.alert("密码只能输入是字母或者数字,请重新输入");
        return false; }
    if(psd.length!=6)
    {
        document.getElementById("psd").value =  '<?php echo ($inf["changeble"]["password"]); ?>';
        layer.alert("密码长度有误");
        return false;
    }
}
function phconfirm() {
    var ph=document.getElementById("phone").value;
    var reg = /^[0-9]+$/;
    if(ph!=""&&!reg.test(ph)){
        document.getElementById("phone").value = '<?php echo ($inf["changeble"]["tel"]); ?>';
        layer.alert("手机号只能输入数字！");
        return false;
    }else if( ph.length != 11){
                document.getElementById("phone").value = '<?php echo ($inf["changeble"]["tel"]); ?>';
        layer.alert("手机号长度不对！");
        return false;
    }
   
    
}
function emailconfirm() {
    var email=document.getElementById("email").value;
    var myreg = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
    if(!myreg.test(email))
    {
        layer.alert('请输入有效的邮箱！');
        document.getElementById("email").value = '<?php echo ($inf["changeble"]["email"]); ?>' ;
        return false;
    }
}

      $(document).ready(function(){
   $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });

});
      $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'B1_A'){
            $("li.see").hide();
            $("ul.see").hide();
        }
    });
</script>
</head>

<body class="body">
<!-- 头部 -->
    <header>

    <!-- 头顶状态栏 -->
        <div class="head">

            <div  class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold; ">
                <h ><?php echo (cookie('user_name')); ?></h>
                    <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom "style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

            </div>
        </div>
    </header>
    <div id="ddm" style="position: fixed;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
        <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
           <li style="padding-left: 10px;padding-top: 10px;"><a href="<?php echo U('Home/generalTeacherUserInf');?>" style="color: black;" >个人信息</a></li>
            <li  style=";padding-left: 10px;padding-top: 10px;"><a id="quit" style="color: black;">退出</a></li>
        </ul>
    </div>
    <!-- 导航栏 -->
   
    <nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 18px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top:488px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 528px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 568px;background-color:#BC2F2E;display: none;"></div>

        <li id="m1"><a href="<?php echo U('Home/generalTeacher');?>">首页</a></li>
        <li style="" id="drp2"><a style="cursor:pointer">教学情况</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style="" id="dm21"><a href="<?php echo U('Home/generalTeacherTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Home/generalTeacherTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a  href="<?php echo U('Home/generalTeacherTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研情况</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Home/generalTeacherResearchPap');?>" >论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Home/generalTeacherResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Home/generalTeacherResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Home/generalTeacherResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Home/generalTeacherResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m2"><a href="<?php echo U('Home/generalTeacherOtherExc');?>">国际交流</a></li>
        <li id="m3"><a href="<?php echo U('Home/generalTeacherOtherWel');?>">公益活动</a></li>
        <li id="m4"><a href="<?php echo U('Home/generalTeacherOtherNews');?>">新闻记录</a></li>
        <li id="m5"><a href="<?php echo U('Home/generalTeacherUserInf');?>">账号管理</a></li>
         <li style="" class="see" id="drp1"><a>查看院内</a></li>
            <ul class="see" style="list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style=""id="dm11"><a href="<?php echo U('Home/generalTeacherCount');?>">院内统计信息</a></li>
            <li style="" id="dm12"><a href="<?php echo U('Home/generalTeacherClassifySearch');?>">按分类查看</a></li>
            <li style="" id="dm13"><a href="<?php echo U('Home/generalTeacherUserFind');?>">按教师查看</a></li>
           
            </ul>
        </ul>
    </nav>
<!-- 主体部分 -->
<div class="main">
        <div class="home">
            <h style="font-weight: bold;">个人信息</h>
        </div>
        <div class="hr0">
            <hr>
        </div>

        <div>
            <table>

                    <tr class="hh2">
                    <th>
                        工号
                    </th>
                    <th>
                        姓名
                    </th>
                    <th>
                        民族
                    </th>
                    <th>
                        性别
                    </th>
                    <th>
                        出生日期
                    </th>
                    <th>
                        年龄
                    </th>
                    <th rowspan="8" style="padding: 0px;width: 180px;">
                        <div style="padding: 0px; margin: 0px;">
                            <div ><h>个人照</h></div>
                            <img id="photo2" src="/MKSYS<?php echo ($inf["changeble"]["photo"]); ?>" style="width: 125px;height: 175px;" >
                            <div style="margin-top: 10px;">
                            <div style="width: 50px;float: left;margin-left: 10%;">
                            <form id="photoupload" style=" ">
                            <input type="file" id="btn-file" name="photo" style="display:none" >
                            <input type="button" id="upload" class="btn" style="background-color: #BC2F2E;color: white;border: none;margin-left:20px;margin-right: 20px; width: 50px;" value="上传">
                            </form></div>
                            <div  style="width: 50px;float: right;margin-right: 30%;">
                            <form id="photodownload" style="">
                             <a id="adownload" href="" download="" style="display: none">点击下载</a>
                            <input type="button" id="download" class="btn" style="  width: 50px;background-color: #BC2F2E;color: white;border: none;margin-right:20px;margin-left: 20px;" value="下载">
                            </form></div>
                            </div>
                            <div style="margin:5px;margin-top: 50px; "><h>比例建议2.5：3.5图片为jpg/png格式</h></div>
                        </div>

                    </th>

                    </tr>
                    <tr class="hh3">
                    <td>
                        <?php echo ($inf["info"]["id"]); ?>
                    </td>
                    <td>
                       <?php echo ($inf["info"]["name"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["info"]["nation"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["info"]["sex"]); ?>
                    <td>
                       <?php echo ($inf["info"]["birthday"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["info"]["age"]); ?>
                    </td>
                    </tr>

                    <tr class="hh2">
                    <th colspan="2">
                        所在系
                    </th>
                    <th>
                        职务
                    </th>
                    <th>
                        职称
                    </th>
                    <th>
                        职称的定职日期
                    </th>
                    <th>
                        岗位级别
                    </th>


                    </tr>
                     <tr class="hh3">
                    <td colspan="2" width="120">
                       <?php echo ($inf["job"]["dep"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["job"]["pos"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["job"]["title"]); ?>
                    </td>
                    <td>
                       <?php echo ($inf["job"]["detm"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["job"]["lv"]); ?>
                    </td>


                    </tr>

                    <tr class="hh2">
                    <th>
                        学校
                    </th>
                    <th>
                        专业
                    </th>
                    <th>
                        毕业时间
                    </th>
                        <th>
                            入职日期
                        </th>
                        <th>
                           政治面貌
                        </th>
                        <th>
                            籍贯
                        </th>
                    </tr>
                    <tr class="hh3">
                    <td>
                        <?php echo ($inf["edu"]["university"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["edu"]["profession"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["edu"]["gratm"]); ?>
                    </td>
                    <td>
                        <?php echo ($inf["job"]["startm"]); ?>
                    </td>
                        <td>
                            <?php echo ($inf["info"]["polistatus"]); ?>
                        </td>
                       <td>
                           <?php echo ($inf["info"]["origin"]); ?>
                       </td>
                    </tr>

                    <tr >
                        <td colspan="2" rowspan="2" style="" >
                        <div><div style="margin-left: -180px;">密码</div>
                        <div>
                        <form action="<?php echo U('Home/changePd');?>" method="POST"  onsubmit="return psdconfirm()">
                        <input type="password" name="pd"  value="<?php echo ($inf["changeble"]["password"]); ?>" id="psd"  style="width: 150px;"> <span id="yin" class="glyphicon glyphicon-eye-open  glyphicon-eye-close"></span><input type="submit" name="submit" value="修改" style="background-color: #BC2F2E;color: white;border: none;margin-left: 5px;"   >
                        </form>
                        </div></div>
                        </td>
                        <td colspan="2" rowspan="2">
                            <div><div style="margin-left: -165px;">手机</div>
                                <div>
                                 <form action="<?php echo U('Home/changeTel');?>" method="POST"  onsubmit ="return phconfirm()">
                                <input type="text" name="tel" value="<?php echo ($inf["changeble"]["tel"]); ?>" id="phone"  style="width: 150px;"> <input type="submit" name="submit" value="修改" style="background-color: #BC2F2E;color: white;border: none;margin-left: 5px;">
                                </form>
                                </div></div>
                        </td>
                        <td colspan="2" rowspan="2">
                            <div><div style="margin-left: -165px;">邮箱</div>
                                <div>
                                <form action="<?php echo U('Home/changeEmail');?>" method="POST"  onsubmit="return  emailconfirm()">
                                <input type="email" name="email" value="<?php echo ($inf["changeble"]["email"]); ?>" id="email"  style="width: 150px;"> <input type="submit" name="submit" value="修改" style="background-color: #BC2F2E;color: white;border: none;margin-left: 5px;">
                                </form>
                                </div></div>
                        </td>
                    </tr>
            </table>
        </div>


</div>

    
</body>
</html>