<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

     <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
      input
      {
        outline: none;
      }
      select
      {
        outline: none;
      }
        .home
        {
            
            width: 121px;
            height: 35px;
            line-height: 35px;
            color: rgba(16, 16, 16, 1);
            font-size: 24px;
            text-align: center;
            font-family: Roboto;

        }
         .hr0
        {
           position: relative;
            top: -5px;
            
            height: 12px;

        }
        table 
        {
            width: 80%;

        }
        table,th,td
        {
             border:3px solid;
            border-color: #A6A6A6 ;
             text-align: center;
        }

        tr.hh2 th
        {

             padding: 5px;
            color: #B8B8B8 ;
            border-color: #A6A6A6;
            width: 120px;
        }
        tr.hh3 td
        {

             padding: 5px;
            width: 120px;
        }
        th td
        {
            width: 120px;
        }
        table
        {
            table-layout:fixed; word-break: break-all; word-wrap: break-word;
        }
    
    </style>
<script type="text/javascript">
   $(document).ready(function(){




    var pageId = '<?php echo ($page); ?>';
       //页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：

if(pageId=='page7')
{
    
    $("#m4").css("background-color","#363536");
    $("#d4").css("display","inline");
}

$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'75px'
    },"fast")}else if(heit=="75px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
    <script>
     /*退出登录*/
        $(document).ready(function(){
             $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });
        });
   $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'C1_B5' || auth == 'C2_B5'){
            $("li.userpd").hide();
            $("li.adminpd").hide();
            if(auth == 'C1_B5'){
                $("h#auth").text("教学秘书");
            }else{
                $("h#auth").text("科研秘书");
            }
        }else{
            $("h#auth").text("超级管理员");
        }
        });
        $(document).ready(function(){
            var isok = "<?php echo ($isok); ?>";
            if(isok==0){
                alert("添加失败！");
            }else if(isok == 1){
                 alert("添加成功！");
            }
            else if(isok==2){
                alert("项目不能为空！");
            }
            else if(isok==3){
                alert("修改失败！");
            }
            else if(isok == 4){
                alert("修改成功！");
            }
                    $.post("<?php echo U('Admin/superAdminUserPdAddEdit');?>",
                        function(data,status){
                      if(status == 'success'){
                        $("img#userphoto").attr("src","/MKSYS"+data['userinfo'][0]['photo']);
                        $("img#userphoto").attr("class",data['userinfo'][0]['id']);
                        $("th#photo").attr("style","padding: 0px;width: 180px;");
                        $("input#id").val(data['login'][0]['id']);
                        $("input#id").attr("readonly","readonly");
                        $("input#name").val(data['userinfo'][0]['name']);
                        $("h#change").text("修改"+data['userinfo'][0]['name']);
                        $("input#nation").val(data['userinfo'][0]['nation']);
                        $("select#sex").val(data['userinfo'][0]['sex']);
                        $("input#birthday").val(data['userinfo'][0]['birthday']);
                        $("input#age").val(data['userinfo'][0]['age']);
                        $("select#dep").val(data['userjob'][0]['dep']);
                        $("select#pos").val(data['userjob'][0]['pos']);
                        $("select#title").val(data['userjob'][0]['title']);
                        $("input#detm").val(data['userjob'][0]['detm']);
                        $("select#lv").val(data['userjob'][0]['lv']);
                        $("input#university").val(data['useredu'][0]['university']);
                        $("input#profession").val(data['useredu'][0]['profession']);
                        $("input#gratm").val(data['useredu'][0]['gratm']);
                        $("input#startm").val(data['userjob'][0]['startm']);
                        $("input#polistatus").val(data['userinfo'][0]['polistatus']);
                        $("input#origin").val(data['userinfo'][0]['origin']);
                        $("input#psd").val(data['login'][0]['pd']);
                        $("input#phone").val(data['userinfo'][0]['tel']);
                        $("input#email").val(data['userinfo'][0]['email']);
            
                            // download图片
                         $("#download").click(function(){
                                
                                $path = data['userinfo'][0]['photo'];
                                // 字符串处理
                                $filename=$path.substring(25);
                                if($filename != ''){
                                    $("#adownload").attr("href","/MKSYS"+$path);
                                    $("#adownload").attr("download",$filename);
                                    // 模拟点击事件，触发下载事件
                                    document.getElementById("adownload").click();
                                }else{
                                    alert("该教师还未上传图片");
                                }
                                
                        });
                      }else if(data == 'cookiefail'){
                         window.location.href = "<?php echo U('Index/index');?>";
                      }
                   });

        });

     
        $(document).ready(function () {
            $("#yin").click(function () {
                $("#yin").toggleClass("glyphicon-eye-close");
                var va=document.getElementById("psd");

                if(va.type=="password") {
                    va.type='text';

                }else {

                    va.type='password';
                }

            });


        });
        function psdconfirm() {
            var psd=document.getElementById("psd").value;
            var zmnumReg=/^[0-9a-zA-Z]*$/;
            if(psd!=""&&!zmnumReg.test(psd)){
                alert("密码只能输入是字母或者数字,请重新输入");
                return false; }
            if(psd.length!=6)
            {
                alert("密码长度有误");
                return false;
            }
        }
        function phconfirm() {
            var ph=document.getElementById("phone").value;
            var reg = /^[0-9]+$/;
            if(ph!=""&&!reg.test(ph)){
                alert("账号只能输入数字！");
                return false;
            }

        }
        function emailconfirm() {
            var email=document.getElementById("email").value;
            var myreg = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
            if(!myreg.test(email))
            {
                alert('请输入有效的邮箱！');
                return false;
            }
        }

    $(document).ready(function(){
        var data = "return";
        $("a#return").click(function(){
            // 删除cookie
            $.post("<?php echo U('Admin/getUserId');?>",{
                data : data
            },function(data){
                if(data == 'success'){
                    window.location.href = "<?php echo U('Admin/superAdminUserPd');?>";
                }else if(data == 'cookiefail'){
                    window.location.href = "<?php echo U('Index/index');?>";
                }
            });
        });
    });
    </script>
</head>
<body class="body">
<!-- 头部 -->
<header>

<!-- 头顶状态栏 -->
    <div class="head">

        <div  class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold; ">
            <h id="auth"></h>
                <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom " style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

        </div>
    </div>
</header>
<div id="ddm" style="position: absolute;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
    <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
        <li  style=";padding-left: 10px;padding-top: 10px;"><a  id="quit" style="color: black;">退出</a></li>
    </ul>
</div>
<!-- 导航栏 -->
<nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top: 68px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 108px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 148px;background-color:#BC2F2E;display: none;"></div>
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 438px;background-color:#BC2F2E;display: none;"></div>

        <li style="" id="drp1"><a style="cursor:pointer">查看院内</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style=""id="dm11"><a href="<?php echo U('Admin/superAdmin');?>">院内统计信息</a></li>
            <li style=""id="dm12"><a>按分类查看</a></li>
            <li style=""id="dm13"><a>按教师查看</a></li>
            </ul>
        <li style="" id="drp2"><a style="cursor:pointer">教学审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style=""id="dm21"><a href="<?php echo U('Admin/superAdminTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Admin/superAdminTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a href="<?php echo U('Admin/superAdminTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Admin/superAdminResearchPap');?>">论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Admin/superAdminResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Admin/superAdminResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Admin/superAdminResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Admin/superAdminResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m1"><a href="<?php echo U('Admin/superAdminOtherExc');?>">国际交流</a></li>
        <li id="m2"><a href="<?php echo U('Admin/superAdminOtherWel');?>">公益活动</a></li>
        <li id="m3"><a href="<?php echo U('Admin/superAdminOtherNews');?>">新闻记录</a></li>
      <li id="m4" class="userpd"><a href="<?php echo U('Admin/superAdminUserPd');?>">账号管理</a></li>
        <li id="m5" class="adminpd"><a href="<?php echo U('Admin/superAdminAdminPd');?>">管理员账号</a></li>
        </ul>
    </nav>


<!-- 主体部分 -->
<div class="main">
    <div class="home">
        <a id="return" href=""><span class="glyphicon glyphicon-menu-left"  style="top: 4px;"></span></a><h id="change" style="font-weight: bold;">添加账号</h>
    </div>
    <div class="hr0">
        <hr>
    </div>

    <div>
    <form  method="POST" action="<?php echo U('Admin/superAdminUserPdAdd');?>">
        <table>

            <tr class="hh2">
                <th>
                    工号
                </th>
                <th>
                    姓名
                </th>
                <th>
                    民族
                </th>
                <th>
                    性别
                </th>
                <th>
                    出生日期
                </th>
                <th>
                    年龄
                </th>
                <th id="photo" rowspan="8" style="display:none;padding: 0px;width: 180px;">
                    <div style="padding: 0px; margin: 0px;">
                        <div ><h>个人照</h></div>
                        <img id="userphoto" class="" src="admin.png" alt="该教师还未上传图片" style="width: 125px;height: 175px;" >
                        <div style="margin-top: 10px;">
                             <a id="adownload" href="" download="" style="display: none">点击下载</a>
                            <input type="button" id="download" class="btn" style="  width: 50px;background-color: #BC2F2E;color: white;border: none;margin-right:20px;margin-left: 20px;" value="下载">
                        </div>
                    </div>

                </th>

            </tr>
            <tr class="hh3">
                <td>
                    <input type="text" name="id" id="id" style="width: 120px;border: none;" >
                </td>
                <td>
                   <input type="text" name="name" id="name" style="width: 120px;border: none;">
                </td>
                <td>
                    <input type="text" name="nation" id="nation" style="width: 120px;border: none;">
                </td>
                <td>
                    <select name="sex" id="sex" style="border: none;">
                        <option>男</option>
                        <option>女</option>
                    </select>
                <td>
                    <input type="date" name="birthday" id="birthday" style="border: none;">
                </td>
                <td>
                    <input type="text" name="age" id="age" style="width: 120px;border: none;">
                </td>
            </tr>

            <tr class="hh2">
                <th colspan="2">
                    所在系
                </th>
                <th>
                    职务
                </th>
                <th>
                    职称
                </th>
                <th>
                    职称的定职日期
                </th>
                <th>
                    岗位级别
                </th>


            </tr>
            <tr class="hh3">
                <td colspan="2" width="120">
                    <select name="dep" id="dep" style="border: none;">
                        <option value="思想政治教育系">思想政治教育系 </option>
                        <option value="马克思主义基本原理系">马克思主义基本原理系</option>
                        <option value="马克思主义中国化研究系">马克思主义中国化研究系</option>
                        <option value="中国近现代史基本问题研究系">中国近现代史基本问题研究系</option>
                        <option value="思修与形势政策系教学成果奖">思修与形势政策系教学成果奖</option>
                    </select>
                </td>
                <td>
                    <select name="pos" id="pos" style="border: none;">
                        <option value="院长">院长 </option>
                        <option value="副院长">副院长</option>
                        <option value="党委书记">党委书记</option>
                        <option value="党委副书记">党委副书记</option>
                        <option value="院长助理">院长助理</option>
                        <option value="系主任">系主任</option>
                        <option value="系副主任">系副主任</option>
                        <option value="办公室主任">办公室主任</option>
                        <option value="教授委员会主任">教授委员会主任</option>
                        <option value="教授委员会副主任">教授委员会副主任</option>
                        <option value="教师">教师</option>
                        <option value="其他">其他</option>
                    </select>
                </td>
                <td>
                    <select name="title" id="title" style="border: none;">
                        <option value="教授">教授 </option>
                        <option value="副教授">副教授</option>
                        <option value="研究员">研究员</option>
                        <option value="副研究员">副研究员</option>
                        <option value="讲师">讲师</option>
                        <option value="助理研究员">助理研究员</option>
                        <option value="助理教授">助理教授</option>


                    </select>
                </td>
                <td>
                    <input type="date" name="detm" id="detm" style="width: 140px;border: none;">
                </td>
                <td>
                    <select name="lv" id="lv" style="border: none;">
                        <option value="学科建设一级">学科建设一级 </option>
                        <option value="学科建设二级">学科建设二级</option>
                        <option value="学科建设三级">学科建设三级</option>
                        <option value="学科建设四级">学科建设四级</option>
                        <option value="专业建设一级">专业建设一级</option>
                        <option value="专业建设二级">专业建设二级</option>
                        <option value="专业建设三级">专业建设三级</option>
                        <option value="专业建设四级">专业建设四级</option>
                        <option value="思政课教学一级">思政课教学一级</option>
                        <option value="思政课教学二级">思政课教学二级</option>
                        <option value="思政课教学三级">思政课教学三级</option>
                        <option value="思政课教学四级">思政课教学四级</option>
                        <option value="思政课教学五级">思政课教学五级</option>
                        <option value="思政课教学六级">思政课教学六级</option>


                    </select>
                </td>


            </tr>

            <tr class="hh2">
                <th>
                    学校
                </th>
                <th>
                    专业
                </th>
                <th>
                    毕业时间
                </th>
                <th>
                    入职日期
                </th>
                <th>
                    政治面貌
                </th>
                <th>
                    籍贯
                </th>
            </tr>
            <tr class="hh3">
                <td>
                    <input type="text" name="university" id="university" style="width: 120px;border: none;">
                </td>
                <td>
                    <input type="text" name="profession" id="profession" style="width: 120px;border: none;">
                </td>
                <td>
                    <input type="date" name="gratm" id="gratm"  style="border: none;">
                </td>
                <td>
                    <input type="date" name="startm" id="startm" style="border: none;">
                </td>
                <td>
                    <input type="text" name="polistatus" id="polistatus" style="width: 120px;border: none;">
                </td>
                <td>
                    <input type="text" name="origin" id="origin" style="width: 120px;border: none;">
                </td>
            </tr>

            <tr >
                <td colspan="2" rowspan="2" style="" >
                    <div><div style="margin-left: -160px;">身份证后六位</div>
                        <div><input id="psd" type="password" name="password" style="width: 150px;border: none;margin-left:-65px;margin-top: 10px;margin-bottom: 10px;"> <span id="yin" class="glyphicon glyphicon-eye-open  glyphicon-eye-close"></span></div></div>
                </td>
                <td colspan="2" rowspan="2">
                    <div><div style="margin-left: -160px;">手机</div>
                        <div><input id="phone" type="text" name="tel" style="width: 150px;margin-left:-30px;margin-top: 10px;margin-bottom: 10px;"></div></div>
                </td>
                <td colspan="2" rowspan="2">
                    <div><div style="margin-left: -160px;">邮箱</div>
                        <div><input id="email" type="email" name="email" style="width: 150px;margin-left:-30px;margin-top: 10px;margin-bottom: 10px;"></div></div>
                </td>
            </tr>
        </table>
        <div style=""><input type="submit" name="submit" value="提交" style="background-color: #BC2F2E;color: white;border: none;width:80px ;height: 30px;margin-top: 10px;"></div>
    </form>
    </div>


</div>


</body>
</html>