<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

    <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <!-- 引入layui -->
    <script type="text/javascript" src="/mksys/Public/syspkg/layer/layer.js"></script>
    <link rel="stylesheet" type="text/css" href="/mksys/Public/syspkg/css/jiaoxue.css">
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
     input
  {
   outline:none;
  }
  select
  {

   outline:none;
  
  }
         .home
        {
            
            width:120px;
            height: 35px;
            line-height: 35px;
            color: rgba(16, 16, 16, 1);
            font-size: 24px;
            text-align: center;
            font-family: Roboto;

        }

        .hr0
        {
           position: relative;
            top: -10px;
           
            height: 12px;

        }
        .xiugai
        {
            color: #009688;
        }
        .shanchu
        {
            color: red;
        }
    </style>
</head>
<script type="text/javascript">
   $(document).ready(function(){


    var pageId = '<?php echo ($page); ?>';
       //页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：
if(pageId=='page7')
{
    
    $("#m4").css("background-color","#363536");
    $("#d4").css("display","inline");
}




$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'75px'
    },"fast")}else if(heit=="75px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
<script>
    /*自动检测*/
    $(document).ready(function(){
        // 自动检测在岗状况
        var ison = '<?php echo ($ison); ?>';
        if(ison == '在岗'){
            $("option#ison-yes").attr("selected","selected");
        }else if(ison == '离岗'){
             $("option#ison-no").attr("selected","selected");
        }
        // 自动检测搜索内容
        var search = '<?php echo ($search); ?>';
        $("input#search").val(search);  
        //  自动检测下拉选框
        var dep = '<?php echo ($dep); ?>';
        if(dep == '所有系'){
            $("option#depall").attr("selected","selected");
        }else if(dep == '思想政治教育系'){
            $("option#dep1").attr("selected","selected");
        }else if(dep == '马克思主义基本原理系'){
            $("option#dep2").attr("selected","selected");
        }else if(dep == '马克思主义中国化研究系'){
            $("option#dep3").attr("selected","selected");
        }else if(dep == '中国近现代史基本问题研究系'){
            $("option#dep4").attr("selected","selected");
        }else if(dep == '思修与形势政策系教学成果奖'){
            $("option#dep5").attr("selected","selected");
        }

    });
           /*编辑项目*/
    $(document).ready(function(){
       $("button.update").click(function(){
           var id = $(this).attr("id");
           $.post("<?php echo U('Admin/getUserId');?>",{
             data : id
           },function(data){
              if(data == 'success'){
                window.location.href = "<?php echo U('Admin/superAdminUserPdAdd');?>";
              }else if(data == 'cookiefail'){
                 window.location.href = "<?php echo U('Index/index');?>";
              }
           });
        });
    });

             $(document).ready(function(){
        /*删除项目*/
        $("button.delete").click(function(){
            var  id = $(this).attr("id");
            layer.confirm('删除账号后，该账号所有的信息将清空并且不可复原，确定删除该账号吗？',{
                    btn:['确定','取消']
                },function () {
                    //删除确定的ajax代码应该放在这里
                     $.post("<?php echo U('Admin/deleteUserPd');?>",{
                        data  : id
                      },
                      function(data,status){
                        if(status == "success"){
                          if(data=='success'){
                            $("tr#"+id).hide();
                          }else if(data=='cookiefail'){
                             window.location.href = "<?php echo U('Index/index');?>";
                          }else{
                            alert("删除失败！");
                          }
                        }         
                      }
                      );
                    layer.closeAll();
                    window.location.reload();
                },
                function () {
                    layer.closeAll();
                });        
        });

        /*退出登录*/
        $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });
       });
    $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'C1_B5' || auth == 'C2_B5'){
            $("li.userpd").hide();
            $("li.adminpd").hide();
             if(auth == 'C1_B5'){
                $("h#auth").text("教学秘书");
            }else{
                $("h#auth").text("科研秘书");
            }
        }else{
            $("h#auth").text("超级管理员");
        }
        });
</script>
<body class="body">
<!-- 头部 -->
<header>

<!-- 头顶状态栏 -->
    <div class="head">

        <div  class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold; ">
            <h id="auth"></h>
                <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom " style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

        </div>
    </div>
</header>
<div id="ddm" style="position: absolute;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
    <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
        <li  style=";padding-left: 10px;padding-top: 10px;"><a  id="quit" style="color: black;">退出</a></li>
    </ul>
</div>
     <!-- 导航栏 -->
   
   <nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top: 68px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 108px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 148px;background-color:#BC2F2E;display: none;"></div>
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 438px;background-color:#BC2F2E;display: none;"></div>

         <li style="" id="drp1"><a style="cursor:pointer">查看院内</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style=""id="dm11"><a href="<?php echo U('Admin/superAdmin');?>">院内统计信息</a></li>
            <li style=""id="dm12"><a>按分类查看</a></li>
            <li style=""id="dm13"><a>按教师查看</a></li>
            </ul>
        <li style="" id="drp2"><a style="cursor:pointer">教学审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style=""id="dm21"><a href="<?php echo U('Admin/superAdminTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Admin/superAdminTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a href="<?php echo U('Admin/superAdminTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Admin/superAdminResearchPap');?>">论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Admin/superAdminResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Admin/superAdminResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Admin/superAdminResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Admin/superAdminResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m1"><a href="<?php echo U('Admin/superAdminOtherExc');?>">国际交流</a></li>
        <li id="m2"><a href="<?php echo U('Admin/superAdminOtherWel');?>">公益活动</a></li>
        <li id="m3"><a href="<?php echo U('Admin/superAdminOtherNews');?>">新闻记录</a></li>
      <li id="m4" class="userpd"><a href="<?php echo U('Admin/superAdminUserPd');?>">账号管理</a></li>
        <li id="m5" class="adminpd"><a href="<?php echo U('Admin/superAdminAdminPd');?>">管理员账号</a></li>
        </ul>
    </nav>
<!-- 主体部分 -->
<div class="main">
    <div class="home">
        <h style="font-weight: bold;">账号管理</h>
    </div>

    <div class="hr0">
        <hr>
    </div>


    
        <div>
         <form id="searchUserInfo" method="POST" action="<?php echo U('Admin/superAdminUserPd');?>">
            <div class="time_select">
                <select  name="ison" style="width: 91px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px;">
                    <option id="ison-yes" value="在岗">在岗</option>
                    <option id="ison-no" value="离岗">离岗</option>

                </select>

            </div>
            <div style="float: left;margin-left:110px ;margin-top: -28px;">
                <select  name="dep" style="width: 200px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px;">
                    <option id="depall" value="所有系">所有系</option>
                    <option id="dep1" value="思想政治教育系">思想政治教育系 </option>
                    <option id="dep2" value="马克思主义基本原理系">马克思主义基本原理系</option>
                    <option id="dep3" value="马克思主义中国化研究系">马克思主义中国化研究系</option>
                    <option id="dep4" value="中国近现代史基本问题研究系">中国近现代史基本问题研究系</option>
                    <option id="dep5" value="思修与形势政策系教学成果奖">思修与形势政策系教学成果奖</option>
                </select>
            </div>
            <div style="float: left;margin-left: 25px; font-size: 17px;margin-top: -28px;  ">
                <input type="text" id="search" name="search" style=" height:30px;border-radius: 7px;color: rgba(136, 136, 136, 1);font-size: 14px;text-align: left;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);padding-left: 4px;" placeholder="请输入教师名称或工号"></div>
            <div style="float: left;margin-left:20px; margin-top: -28px; "> 

            <input  type="submit" name="submit" style="background-color: rgba(188, 47, 46, 1);color: white;border:none;border-radius: 7px;width: 80px;height: 30px;text-align: center;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);" value="搜索" > 
</div>
</form>
            <div style="float: left;margin-left: 30px; margin-top: -28px;  "> <button style="width: 100px;height: 30px;line-height: 20px;border-radius: 7px;text-align: center;color: white;border:none;color: rgba(255, 255, 255, 1);box-shadow: 0px 0px 2px 0px #DB9D40 ;background-color: #DB9D40;
"><a href="<?php echo U('Admin/superAdminUserPdAdd');?>" style="color: white">添加账号</a></button></div>
        </div>

    

    
    
        <table>
            <thead>
            <tr>
                <td>
                    工号
                </td>
                <td>
                    教师姓名
                </td>
                <td>
                    所属系
                </td>
                <td>
                    职务
                </td>
                <td>
                    职称
                </td>

                <td>
                    岗位级别
                </td>
                <td>
                    操作
                </td>
            </tr>
            </thead>
            <tbody id="list">
     <?php if(is_array($adminUser)): $i = 0; $__LIST__ = $adminUser;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$au): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($au['id']); ?>">
        <td id="<?php echo ($au['id']); ?>-id"><?php echo ($au['id']); ?></td>
        <td id="<?php echo ($au['id']); ?>-name"><?php echo ($au['name']); ?></td>
        <td id="<?php echo ($au['id']); ?>-dep"><?php echo ($au['dep']); ?></td>
        <td id="<?php echo ($au['id']); ?>-pos"><?php echo ($au['pos']); ?></td>
        <td id="<?php echo ($au['id']); ?>-title"><?php echo ($au['title']); ?></td>
        <td id="<?php echo ($au['id']); ?>-lv"><?php echo ($au['lv']); ?></td>
        <td><button class="update" id="<?php echo ($au['id']); ?>">修改</button>  <button class="delete" id="<?php echo ($au['id']); ?>">删除</button></td>
      </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>




</body>
</html>