<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--导入jQuery-->
     <script type="text/javascript" src="/libSys/Public/syspkg/jquery-3.2.1.min.js"></script>
    <!--引入Bootstrap-->
    <link href="/libSys/Public/syspkg/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/libSys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/libSys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
     input
      {
        outline: none;
      }
      select
        {

              outline: none;
        }
        html
        {
            width: 100%;
            height: 100%;
        }
    body
    {

        width: 100%;
        height: 100%;

    }
    .head
    {
        position: relative;
        width: 100%;
        height: 13%;
        line-height: 52px;
        background-color: #962C2C;
        color: rgba(255, 255, 255, 1);
        font-size: 36px;
        text-align: left;
        font-family: Roboto;

    }
    .bd
    {   position: relative;
        width: 100%;
        height: 74%;
        background-image:url("/libSys/Public/syspkg/images/back.jpg") ;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;

    }
    footer
    {
        background-color: #962C2C;
        width: 100%;
        height: 13%;
    }
    .main
    {

      position: absolute;

        right:10% ;
        top:50%;
        margin-top:-195px;
        width: 444px;
        height: 389px;
        line-height: 20px;
        border-radius: 20px;
        background-color: rgba(54, 53, 54, 1);
        text-align: center;


    }
    .login
    {
        position: relative;
        left:20px;
        top:37px;
        width: 400px;
        height: 41px;
        line-height: 41px;
        color: rgba(255, 255, 255, 1);
        font-size: 26px;
        text-align: center;
        font-family: Roboto;

    }
    .id
    {   
        position: relative;
        top: 60px;
        padding-left: 10px;
        width: 279px;
        height: 50px;
        border-radius: 10px;
        color: rgba(136, 136, 136, 1);
        font-size: 14px;
        text-align: left;
        font-family: Roboto;
        border: 1px solid rgba(187, 187, 187, 1);

    }
    .pswd
    {   
        position: relative;
        padding-left: 10px;
        top: 90px;
        width: 279px;
        height: 50px;
        border-radius: 10px;
        color: rgba(136, 136, 136, 1);
        font-size: 14px;
        text-align: left;
        font-family: Roboto;
        border: 1px solid rgba(187, 187, 187, 1);

    }
    .tips
    {
        position: relative;
        left: 81px;
        top: 48px;
        width: 144px;
        height: 20px;
        line-height: 19px;
        color: rgba(255, 255, 255, 1);
        font-size: 13px;
        text-align: center;
        font-family: Roboto;

    }
    .submit
    {
        position: relative;
        left: px;
        top: 138px;
        width: 279px;
        height: 50px;
        border-radius: 10px;
        border: none;
        background-color: rgba(188, 47, 46, 1);
        color: rgba(255, 255, 255, 1);
        font-size: 18px;
        text-align: center;
        font-family: Microsoft Yahei;

    }
    .forget
    {
        position: relative;
        left: 191px;
        top: 130px;
        width: 71px;
        height: 20px;
        line-height: 20px;
        font-size: 14px;
        text-align: center;
        font-family: Roboto;

    }
    </style>
</head>
<script>

function form_confirm()
{
    var id=document.getElementById("iid").value
    var psd=document.getElementById("psd").value
    if (id.length!=10)
    {
        alert("工号长度有误");
        return false; 
    }
      var reg = /^[0-9]+$/;
    if(id!=""&&!reg.test(id)){ 
    alert("账号只能输入数字！");
    return false; 
    } 
    var zmnumReg=/^[0-9a-zA-Z]*$/; 
    if(psd!=""&&!zmnumReg.test(psd)){ 
    alert("密码只能输入是字母或者数字,请重新输入");
    return false; }
    if(psd.length!=6)
    {
        alert("密码长度有误");
        return false; 
    }
}
</script>
<body class="bodyy" >
<!-- 头部 -->
<header class="head">
    <div  style="float: left;margin-top: 30px;"><img src="/libSys/Public/syspkg/images/tip.png" style="height: 60px;width: 60px;margin-left: 10px;"><img src="/libSys/Public/syspkg/images/name.png" style="width: 249px;height: 51px;margin-left: 20px;"></div>
   <div style="float: left;margin-left: 36px;"><h style="height: 120px; line-height: 120px;"> 马克思主义学院</h></div>
</header>
<!-- 主体 -->
<div class="bd">
<div class="main">
    <div class="login">
        <img style="height: 40px;width: 40px;" src="/libSys/Public/syspkg/images/app.png" >“智慧马院”信息化管理平台
    </div>

    <form method="post" onsubmit="return form_confirm()" action="<?php echo U('Index/login');?>">
        <fieldset>
        <!-- id框 -->
            <input id="iid" type="text" name="GH" class="id"  placeholder="请输入工号" maxlength="10">
            <!-- 密码框 -->
            <input id="psd"   type="password" name="PSW" class="pswd" placeholder="请输入密码" maxlength="6">
            <!-- 登陆按钮 -->
            <input   id="sb" type="submit" name="SB" class="submit" value="登录" >
        </fieldset>

    </form>
    <div class="tips">
        <h name="tips">*初始密码为身份证后6位</h>
    </div>
    <div class="forget">
        <a style="color: white;" href="<?php echo U('Index/forgetpd');?>">忘记密码？</a>
    </div>

</div>
</div>
<footer>
    <div style="width: 400px;height: 26px;line-height: 26px;color: rgba(255, 255, 255, 1);font-size: 18px;font-family: Roboto;left: 1%;top: 70%;position: relative;">
<h > Copyright © 2018 NWPU. All Rights Reserved.</h></div>
</footer>
</body>
</html>