<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

     <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <!-- 引入layui -->
    <script type="text/javascript" src="/mksys/Public/syspkg/layer/layer.js"></script>
    <link rel="stylesheet" type="text/css" href="/mksys/Public/syspkg/css/jiaoxue.css">
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
    <script type="text/javascript" src="/mksys/Public/syspkg/js/dropdown.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
     input
  {
   outline:none;
  }

        select
        {
            width: 91px;
            height: 30px;
             border-radius: 10px;outline:none;
        }

        .hr0
        {
           position: relative;
            top: -10px;
           
            height: 12px;

        }
       
    </style>
    <script type="text/javascript">
   $(document).ready(function(){

var pageId = '<?php echo ($page); ?>';
       //页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：
if(pageId=='page12')
{
    $("#drp1").click();
    $("#m12").css("background-color","#363536");
    $("#d12").css("display","inline");
}



$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'75px'
    },"fast")}else if(heit=="75px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
<script>
          /*自动检测*/
    $(document).ready(function(){
        // 自动检测年份
        var years = '<?php echo ($years); ?>';
        if(years == '时间不限'){
            $("option#years-all").attr("selected","selected");
        }else if(years == '2017'){
             $("option#years-2017").attr("selected","selected");
        }else if(years == '2018'){
            $("option#years-2018").attr("selected","selected");
        }
        //  自动检测下拉选框
        var dep = '<?php echo ($dep); ?>';
        if(dep == '所有系'){
            $("option#depall").attr("selected","selected");
        }else if(dep == '思想政治教育系'){
            $("option#dep1").attr("selected","selected");
        }else if(dep == '马克思主义基本原理系'){
            $("option#dep2").attr("selected","selected");
        }else if(dep == '马克思主义中国化研究系'){
            $("option#dep3").attr("selected","selected");
        }else if(dep == '中国近现代史基本问题研究系'){
            $("option#dep4").attr("selected","selected");
        }else if(dep == '思修与形势政策系教学成果奖'){
            $("option#dep5").attr("selected","selected");
        }
        // 自动检测status
        var part=1;
        var status = '<?php echo ($status); ?>';
        if(status == '已通过'){
            $("option#yes").attr("selected","selected");
            part = 1;
            $("#part1").show();
            $("#part2").hide();
            $("#part3").hide();
        }else if(status == '待审核'){
            $("option#wait").attr("selected","selected");
            part = 2;
            $("#part2").show();
            $("#part1").hide();
            $("#part3").hide();
        }else if(status== '未通过'){
            $("option#no").attr("selected","selected");
            part = 3;
            $("#part3").show();
            $("#part2").hide();
            $("#part1").hide();
        }
        // 自动检测ptype
        var ptype = '<?php echo ($ptype); ?>';
        if(part == 1){
            if(ptype == '教学成果奖'){
                $("option#teachach").attr("selected","selected");
                $("#table1").show();
                $("#table2").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '教改立项/精品课程类'){
                $("option#teachpro").attr("selected","selected");
                $("#table2").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '教材出版'){
                $("option#teachtbp").attr("selected","selected");
                $("#table3").show();
                $("#table1").hide();
                $("#table2").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '论文发表'){
                $("option#researchpap").attr("selected","selected");
                $("#table4").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table2").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '学术专著/译著出版'){
                $("option#researchmpb").attr("selected","selected");
                $("#table5").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table2").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '科研成果奖'){
                $("option#researchach").attr("selected","selected");
                $("#table6").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table2").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '主持科研项目'){
                $("option#researchpro").attr("selected","selected");
                $("#table7").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table2").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '基金类'){
                $("option#researchfund").attr("selected","selected");
                $("#table8").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table2").hide();
                $("#table9").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '国际交流'){
                $("option#otherexc").attr("selected","selected");
                $("#table9").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table2").hide();
                $("#table10").hide();
                $("#table11").hide();
            }else if(ptype == '公益活动'){
                $("option#otherwel").attr("selected","selected");
                $("#table10").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table2").hide();
                $("#table11").hide();
            }else if(ptype == '新闻记录'){
                $("option#othernews").attr("selected","selected");
                $("#table11").show();
                $("#table1").hide();
                $("#table3").hide();
                $("#table4").hide();
                $("#table5").hide();
                $("#table6").hide();
                $("#table7").hide();
                $("#table8").hide();
                $("#table9").hide();
                $("#table2").hide();
                $("#table10").hide();
            }
        }else if(part == 2){
            if(ptype == '教学成果奖'){
                $("option#teachach").attr("selected","selected");
                $("#table12").show();
                $("#table22").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '教改立项/精品课程类'){
                $("option#teachpro").attr("selected","selected");
                $("#table22").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '教材出版'){
                $("option#teachtbp").attr("selected","selected");
                $("#table32").show();
                $("#table12").hide();
                $("#table22").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '论文发表'){
                $("option#researchpap").attr("selected","selected");
                $("#table42").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table22").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '学术专著/译著出版'){
                $("option#researchmpb").attr("selected","selected");
                $("#table52").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table22").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '科研成果奖'){
                $("option#researchach").attr("selected","selected");
                $("#table62").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table22").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '主持科研项目'){
                $("option#researchpro").attr("selected","selected");
                $("#table72").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table22").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '基金类'){
                $("option#researchfund").attr("selected","selected");
                $("#table82").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table22").hide();
                $("#table92").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '国际交流'){
                $("option#otherexc").attr("selected","selected");
                $("#table92").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table22").hide();
                $("#table102").hide();
                $("#table112").hide();
            }else if(ptype == '公益活动'){
                $("option#otherwel").attr("selected","selected");
                $("#table102").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table22").hide();
                $("#table112").hide();
            }else if(ptype == '新闻记录'){
                $("option#othernews").attr("selected","selected");
                $("#table112").show();
                $("#table12").hide();
                $("#table32").hide();
                $("#table42").hide();
                $("#table52").hide();
                $("#table62").hide();
                $("#table72").hide();
                $("#table82").hide();
                $("#table92").hide();
                $("#table22").hide();
                $("#table102").hide();
            }
        }else if(part == 3){
            if(ptype == '教学成果奖'){
                $("option#teachach").attr("selected","selected");
                $("#table13").show();
                $("#table23").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '教改立项/精品课程类'){
                $("option#teachpro").attr("selected","selected");
                $("#table23").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '教材出版'){
                $("option#teachtbp").attr("selected","selected");
                $("#table33").show();
                $("#table13").hide();
                $("#table23").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '论文发表'){
                $("option#researchpap").attr("selected","selected");
                $("#table43").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table23").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '学术专著/译著出版'){
                $("option#researchmpb").attr("selected","selected");
                $("#table53").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table23").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '科研成果奖'){
                $("option#researchach").attr("selected","selected");
                $("#table63").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table23").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '主持科研项目'){
                $("option#researchpro").attr("selected","selected");
                $("#table73").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table23").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '基金类'){
                $("option#researchfund").attr("selected","selected");
                $("#table83").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table23").hide();
                $("#table93").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '国际交流'){
                $("option#otherexc").attr("selected","selected");
                $("#table93").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table23").hide();
                $("#table103").hide();
                $("#table113").hide();
            }else if(ptype == '公益活动'){
                $("option#otherwel").attr("selected","selected");
                $("#table103").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table2").hide();
                $("#table113").hide();
            }else if(ptype == '新闻记录'){
                $("option#othernews").attr("selected","selected");
                $("#table113").show();
                $("#table13").hide();
                $("#table33").hide();
                $("#table43").hide();
                $("#table53").hide();
                $("#table63").hide();
                $("#table73").hide();
                $("#table83").hide();
                $("#table93").hide();
                $("#table23").hide();
                $("#table103").hide();
            }
        }
        
    });
     /*退出登录*/
        $(document).ready(function(){
             $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });
        });

    $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'C1_B5' || auth == 'C2_B5'){
            $("li.userpd").hide();
            $("li.adminpd").hide();
            if(auth == 'C1_B5'){
                $("h#auth").text("教学秘书");
            }else{
                $("h#auth").text("科研秘书");
            }
        }else{
            $("h#auth").text("超级管理员");
        }
        });

     $(document).ready(function(){
        $("select#dDown1").change(function(){
            $("input#submit").click();
        });
        $("select#dDown2").change(function(){
            $("input#submit").click();
        });
        $("select#dep").change(function(){
            $("input#submit").click();
        });
        $("select#years").change(function(){
            $("input#submit").click();
        });
    });

    //下载excel表格
    $(document).ready(function(){
        //下载excel
        $("#download").click(function(){
            // 获取years和dep
            var status = $("#dDown1").val();
            var years = $("#years").val();
            var dep = $("#dep").val();
            var ptype = $("#dDown2").val();
            layer.confirm("你将下载“马克思学院"+years+"年度"+dep+status+"的"+ptype+"成果汇总表”", {
                btn: ['确定','取消'], //按钮
                   time:10000
                }, function(){
                   var url = "<?php echo U('Admin/excelClassify?years=years1&dep=dep1&status=status1&ptype=ptype1');?>";
                   url = url.replace("years1",years);
                   url = url.replace("dep1",dep);
                   url = url.replace("status1",status);
                   url = url.replace("ptype1",ptype);
                   document.location.href =url;
                }, function(){
                //取消
                   layer.closeAll();
            });
           
        });
    });

</script>
</head>

<body class="body">
<!-- 头部 -->
    <header>

    <!-- 头顶状态栏 -->
        <div class="head">

            <div  class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold; ">
                <h id="auth"></h>
                    <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom "style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

            </div>
        </div>
    </header>
    <div id="ddm" style="position: fixed;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
        <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
            <li  style=";padding-left: 10px;padding-top: 10px;"><a id="quit" style="color: black;">退出</a></li>
        </ul>
    </div>
    <!-- 导航栏 -->
   
  <nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top: 68px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 108px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 148px;background-color:#BC2F2E;display: none;"></div>
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 438px;background-color:#BC2F2E;display: none;"></div>

         <li style="" id="drp1"><a style="cursor:pointer">查看院内</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style=""id="dm11"><a href="<?php echo U('Admin/superAdmin');?>">院内统计信息</a></li>
            <li style=""id="dm12"><a href="<?php echo U('Admin/superAdminClassifySearch');?>">按分类查看</a></li>
            <li style=""id="dm13"><a href="<?php echo U('Admin/superAdminUserFind');?>">按教师查看</a></li>
            </ul>
        <li style="" id="drp2"><a style="cursor:pointer">教学审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style=""id="dm21"><a href="<?php echo U('Admin/superAdminTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Admin/superAdminTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a href="<?php echo U('Admin/superAdminTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Admin/superAdminResearchPap');?>">论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Admin/superAdminResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Admin/superAdminResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Admin/superAdminResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Admin/superAdminResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m1"><a href="<?php echo U('Admin/superAdminOtherExc');?>">国际交流</a></li>
        <li id="m2"><a href="<?php echo U('Admin/superAdminOtherWel');?>">公益活动</a></li>
        <li id="m3"><a href="<?php echo U('Admin/superAdminOtherNews');?>">新闻记录</a></li>
      <li id="m4" class="userpd"><a href="<?php echo U('Admin/superAdminUserPd');?>">账号管理</a></li>
        <li id="m5" class="adminpd"><a href="<?php echo U('Admin/superAdminAdminPd');?>">管理员账号</a></li>
        </ul>
    </nav>
    
    
<div class="main" style="">
<div class="home">
            <div style="display: inline-block;"><h style="font-weight: bold;">分类查看</h></div>
            <div style="display: inline-block;"><button id="download" class="glyphicon glyphicon-save" style="border:0;background: white;color:#1979CA;" ></button></div>
        </div>

        <div class="hr0">
            <hr>
        </div>  
        <form method="POST" action="<?php echo U('Admin/superAdminClassifySearch');?>">    
            <select name="status" id="dDown1" style="width: 91px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px;padding-left:5px;" onchange="ddChange2()">
                        <option id="yes" value="已通过">已通过</option>
                        <option id="wait" value="待审核">待审核</option>
                        <option id="no" value="未通过">未通过</option>
                </select>     
                <select  name="years" id="years" style="width: 91px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px;margin-left: 20px;padding-left:5px; ">
                        <option id="years-all" value="时间不限">时间不限</option>
                        <option id="years-2017" value="2017">2017</option>
                        <option id="years-2018" value="2018">2018</option>
                </select>
                
          
           
                <select  name="dep" id="dep" style="width: 200px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px; margin-left: 20px;padding-left:5px;">
                         <option id="depall" value="所有系">所有系</option>
                        <option id="dep1" value="思想政治教育系">思想政治教育系</option>
                        <option id="dep2" value="马克思主义基本原理系">马克思主义基本原理系</option>
                        <option id="dep3" value="马克思主义中国化研究系">马克思主义中国化研究系</option>
                        <option id="dep4" value="中国近现代史基本问题研究系">中国近现代史基本问题研究系</option>
                        <option id="dep5" value="思修与形势政策系教学成果奖">思修与形势政策系教学成果奖</option>
                </select>
          
           
                <select id="dDown2" name="ptype" style="width: 250px;height: 30px;line-height: 17px;color: rgba(16, 16, 16, 1);font-size: 12px;box-shadow: 0px 0px 2px 0px rgba(188, 47, 46, 1);font-family: Microsoft Yahei;border: 1px solid rgba(188, 47, 46, 1);border-radius: 7px; margin-left: 20px;padding-left:5px;"
                onchange="ddChange()">
                        <option id="teachach" value="教学成果奖">教学成果奖 </option>
                        <option id="teachpro" value="教改立项/精品课程类">教改立项/精品课程类</option>
                        <option id="teachtbp" value="教材出版">教材出版</option>
                        <option id="researchpap" value="论文发表">论文发表</option>
                        <option id="researchmpb" value="学术专著/译著出版">学术专著/译著出版</option>
                        <option id="researchach" value="科研成果奖">科研成果奖</option>
                        <option id="researchpro" value="主持科研项目">主持科研项目</option>
                        <option id="researchfund" value="基金类">基金类</option>
                        <option id="otherexc" value="国际交流">国际交流</option>
                        <option id="otherwel" value="公益活动">公益活动</option>
                        <option id="othernews" value="新闻记录">新闻记录</option>
                </select>
           
            
            <input type="submit" name="submit" id="submit" value="查询" style="width: 80px;height: 30px;line-height: 20px;border-radius: 7px;text-align: center;color: white;border:none;color: rgba(255, 255, 255, 1);box-shadow: 0px 0px 2px 0px #DB9D40 ;background-color: #DB9D40;margin-left: 20px;display: none">
            </form>
       
        <div id="part1">

        <table id="table1" >
            <thead>
                <tr>
                <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">

                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-lv"><?php echo ($ta['lv']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>

        <table id="table2" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>教改立项/精品课程名称</td>
                    <td>类别</td>
                    <td>立项时间</td>
                    <td>总经费</td>
                    <td>已到款</td>
                    <td>剩余经费</td>
                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tp"><?php echo ($ta['tp']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-fund"><?php echo ($ta['fund']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-paid"><?php echo ($ta['paid']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-remain"><?php echo ($ta['remain']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                
            </tbody>
        </table>

        <table id="table3" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        出版教材名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        署名情况
                    </td>
                     <td>
                        出版时间
                    </td>
                     
                </tr>
            </thead>
            <tbody>
               <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-signature"><?php echo ($ta['signature']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
        
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>       

         <table  id="table4" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        发表论文名称
                    </td>
                    <td>
                        刊物名称
                    </td>
                     <td>
                        卷期号
                    </td>
                     <td>
                        合著情况
                    </td>
                    <td>
                        期刊级别
                    </td>
                    <td>
                        发表时间
                    </td>
                     
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-vnum"><?php echo ($ta['vnum']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-lv"><?php echo ($ta['lv']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
               
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
               
            </tbody>
        </table>

        <table id="table5" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        专著、译著名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        合著情况
                    </td>
                     <td>
                        出版时间
                    </td>
                    
                </tr>
            </thead>
            <tbody>
                  <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                 <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
             
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table  id="table6" style="display:none;"> 
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                    
                </tr>
            </thead>
            <tbody>
                   <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-lv"><?php echo ($ta['lv']); ?></td>
           
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table id="table7" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        主持科研项目名称
                    </td>
                    <td>
                        经费资助来源
                    </td>
                     <td>
                        期限
                    </td>
                     <td>
                        总经费
                    </td>
                    <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>
                    <td>
                        获批时间
                    </td>
                    
                </tr>
            </thead>
            <tbody>
             <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                  <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-source"><?php echo ($ta['source']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-deadline"><?php echo ($ta['deadline']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-fund"><?php echo ($ta['fund']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-paid"><?php echo ($ta['paid']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-remain"><?php echo ($ta['remain']); ?></td>
                    
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>


            <table id="table8" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        基金名称
                    </td>
                    <td>
                        获批时间
                    </td>
                     <td>
                        总经费
                    </td>
                     <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>
                   
                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-fund"><?php echo ($ta['fund']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-paid"><?php echo ($ta['paid']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-remain"><?php echo ($ta['remain']); ?></td>
                    
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table id="table9" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        国家(境外)
                    </td>
                    <td>
                        时间段
                    </td>
                     <td>
                        地点
                    </td>
                     <td>
                        学校
                    </td>
                    <td>
                        内容
                    </td>
                   
                </tr>
            </thead>
            <tbody>
      <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                 <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-country"><?php echo ($ta['country']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tmin"><?php echo ($ta['tmin']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-place"><?php echo ($ta['place']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-sch"><?php echo ($ta['sch']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-content"><?php echo ($ta['content']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>
         <table id="table10" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                       时间
                    </td>
                    <td>
                        地点
                    </td>
                     <td>
                        内容
                    </td>
                 
                     
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                   <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-place"><?php echo ($ta['place']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-content"><?php echo ($ta['content']); ?></td>
                  
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>
        <table id="table11" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        发布要求
                    </td>
                    <td>
                        标题
                    </td>
                     <td>
                        内容
                    </td>
                   
                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                  <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                   <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-rep"><?php echo ($ta['rep']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-title"><?php echo ($ta['title']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-content"><?php echo ($ta['content']); ?></td>
                   
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

</div>
<div id="part2" style="display: none;">

        <table id="table12" >
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                    
                </tr>
            </thead>
            <tbody>
               <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-lv"><?php echo ($ta['lv']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>

            </tbody>
        </table>

        <table id="table22" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>教改立项/精品课程名称</td>
                    <td>类别</td>
                    <td>立项时间</td>
                    <td>总经费</td>
                    <td>已到款</td>
                    <td>剩余经费</td>
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tp"><?php echo ($ta['tp']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-fund"><?php echo ($ta['fund']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-paid"><?php echo ($ta['paid']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-remain"><?php echo ($ta['remain']); ?></td>
                
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>

        <table id="table32" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        出版教材名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        署名情况
                    </td>
                     <td>
                        出版时间
                    </td>
                   
                </tr>
            </thead>
            <tbody>
                 <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-signature"><?php echo ($ta['signature']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>       

         <table  id="table42" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        发表论文名称
                    </td>
                    <td>
                        刊物名称
                    </td>
                     <td>
                        卷期号
                    </td>
                     <td>
                        合著情况
                    </td>
                    <td>
                        期刊级别
                    </td>
                    <td>
                        发表时间
                    </td>
                   
                </tr>
            </thead>
            <tbody>
                <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
              <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
              <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-vnum"><?php echo ($ta['vnum']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-lv"><?php echo ($ta['lv']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
               
            </tbody>
        </table>

        <table id="table52" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        专著、译著名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        合著情况
                    </td>
                     <td>
                        出版时间
                    </td>
                 
                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
              <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
              <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
               
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table  id="table62" style="display:none;"> 
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                  
                     
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
              <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
               <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-lv"><?php echo ($ta['lv']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
   
                </tbody>
                </table>

        <table id="table72" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        主持科研项目名称
                    </td>
                    <td>
                        经费资助来源
                    </td>
                     <td>
                        期限
                    </td>
                     <td>
                        总经费
                    </td>
                    <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>
                    <td>
                        获批时间
                    </td>
                 

                </tr>
            </thead>
            <tbody>
             <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-source"><?php echo ($ta['source']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-deadline"><?php echo ($ta['deadline']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-fund"><?php echo ($ta['fund']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-paid"><?php echo ($ta['paid']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-remain"><?php echo ($ta['remain']); ?></td>
                  
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>


            <table id="table82" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        基金名称
                    </td>
                    <td>
                        获批时间
                    </td>
                     <td>
                        总经费
                    </td>
                     <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>

                </tr>
            </thead>
            <tbody>
            <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-fund"><?php echo ($ta['fund']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-paid"><?php echo ($ta['paid']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-remain"><?php echo ($ta['remain']); ?></td>
                   
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table id="table92" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        国家(境外)
                    </td>
                    <td>
                        时间段
                    </td>
                     <td>
                        地点
                    </td>
                     <td>
                        学校
                    </td>
                    <td>
                        内容
                    </td>
                   
                </tr>
            </thead>
            <tbody>
                  <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
               <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-country"><?php echo ($ta['country']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tmin"><?php echo ($ta['tmin']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-place"><?php echo ($ta['place']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-sch"><?php echo ($ta['sch']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-content"><?php echo ($ta['content']); ?></td>
               
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>
         <table id="table102" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                       时间
                    </td>
                    <td>
                        地点
                    </td>
                     <td>
                        内容
                    </td>
                  
                     
                </tr>
            </thead>
            <tbody>
             <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-tm"><?php echo ($ta['tm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-place"><?php echo ($ta['place']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-content"><?php echo ($ta['content']); ?></td>
                   
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
               
                </tbody>
                </table>
        <table id="table112" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        发布要求
                    </td>
                    <td>
                        标题
                    </td>
                     <td>
                        内容
                    </td>
                     
                </tr>
            </thead>
            <tbody>
           <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-rep"><?php echo ($ta['rep']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-title"><?php echo ($ta['title']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-content"><?php echo ($ta['content']); ?></td>
                   
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

</div>
<div id="part3" style="display: none;">

        <table id="table13" >
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                      <td>
                        未通过理由
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-lv"><?php echo ($ta['lv']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
               

            </tbody>
        </table>

        <table id="table23" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>教改立项/精品课程名称</td>
                    <td>类别</td>
                    <td>立项时间</td>
                    <td>总经费</td>
                    <td>已到款</td>
                    <td>剩余经费</td>
                      <td>
                        未通过理由
                    </td>
                </tr>
            </thead>
            <tbody>
               <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tp"><?php echo ($ta['tp']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-fund"><?php echo ($ta['fund']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-paid"><?php echo ($ta['paid']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-remain"><?php echo ($ta['remain']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
            </tbody>
        </table>

        <table id="table33" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        出版教材名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        署名情况
                    </td>
                     <td>
                        出版时间
                    </td>
                     <td>
                        未通过理由
                    </td>
                  
                </tr>
            </thead>
            <tbody>
                  <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-signature"><?php echo ($ta['signature']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>

            </tbody>
        </table>       

         <table  id="table43" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        发表论文名称
                    </td>
                    <td>
                        刊物名称
                    </td>
                     <td>
                        卷期号
                    </td>
                     <td>
                        合著情况
                    </td>
                    <td>
                        期刊级别
                    </td>
                    <td>
                        发表时间
                    </td>
                      <td>
                        未通过理由
                    </td>
                  
                </tr>
            </thead>
            <tbody>
                <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-vnum"><?php echo ($ta['vnum']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-lv"><?php echo ($ta['lv']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
               
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
               
            </tbody>
        </table>

        <table id="table53" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        专著、译著名称
                    </td>
                    <td>
                        出版社
                    </td>
                     <td>
                        合著情况
                    </td>
                     <td>
                        出版时间
                    </td>
                     <td>
                        未通过理由
                    </td>
                   
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-pub"><?php echo ($ta['pub']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-partner"><?php echo ($ta['partner']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table  id="table63" style="display:none;"> 
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        获奖名称
                    </td>
                    <td>
                        设奖部门            
                    </td>
                     <td>
                        获奖时间
                    </td>
                     <td>
                        奖励等级
                    </td>
                     <td>
                        未通过理由
                    </td>
                   
                </tr>
            </thead>
            <tbody>
               <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-name"><?php echo ($ta['name']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-dep"><?php echo ($ta['dep']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-tm"><?php echo ($ta['tm']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-YES-lv"><?php echo ($ta['lv']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table id="table73" style="display:none;">
            <thead>
                <tr>
                    <td>
                        教师姓名
                    </td>
                    <td>
                        主持科研项目名称
                    </td>
                    <td>
                        经费资助来源
                    </td>
                     <td>
                        期限
                    </td>
                     <td>
                        总经费
                    </td>
                    <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>
                    <td>
                        获批时间
                    </td>
                     <td>
                        未通过理由
                    </td>
                  
                </tr>
            </thead>
            <tbody>
             <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                  <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                  <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-source"><?php echo ($ta['source']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-deadline"><?php echo ($ta['deadline']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-fund"><?php echo ($ta['fund']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-paid"><?php echo ($ta['paid']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-remain"><?php echo ($ta['remain']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
                   
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>


            <table id="table83" style="display:none;">
            <thead>
                <tr>
                <td>
                        教师姓名
                    </td>
                    <td>
                        基金名称
                    </td>
                    <td>
                        获批时间
                    </td>
                     <td>
                        总经费
                    </td>
                     <td>
                        已到款
                    </td>
                    <td>
                        剩余经费
                    </td>
                     <td>
                        未通过理由
                    </td>
                   
                </tr>
            </thead>
            <tbody>
           <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-name"><?php echo ($ta['name']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-stm"><?php echo ($ta['stm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-fund"><?php echo ($ta['fund']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-paid"><?php echo ($ta['paid']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-remain"><?php echo ($ta['remain']); ?></td>
                     <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
                  
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

        <table id="table93" style="display:none;">
            <thead>
                <tr>
                <td>
                        教师姓名
                    </td>
                    <td>
                        国家(境外)
                    </td>
                    <td>
                        时间段
                    </td>
                     <td>
                        地点
                    </td>
                     <td>
                        学校
                    </td>
                    <td>
                        内容
                    </td>
                     <td>
                        未通过理由
                    </td>
                   
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-country"><?php echo ($ta['country']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tmin"><?php echo ($ta['tmin']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-place"><?php echo ($ta['place']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-sch"><?php echo ($ta['sch']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-content"><?php echo ($ta['content']); ?></td>
                <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>
              
              </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>
         <table id="table103" style="display:none;">
            <thead>
                <tr>
                <td>
                        教师姓名
                    </td>
                    <td>
                       时间
                    </td>
                    <td>
                        地点
                    </td>
                     <td>
                        内容
                    </td>

                     <td>
                        未通过理由
                    </td>
                
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                  <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-tm"><?php echo ($ta['tm']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-place"><?php echo ($ta['place']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-content"><?php echo ($ta['content']); ?></td>    
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>  
                 
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>
        <table id="table113" style="display:none;">
            <thead>
                <tr>
                <td>
                        教师姓名
                    </td>
                    <td>
                        发布要求
                    </td>
                    <td>
                        标题
                    </td>
                     <td>
                        内容
                    </td>
                   
                    <td>
                        未通过理由
                    </td>
                </tr>
            </thead>
            <tbody>
              <?php if(is_array($array)): $i = 0; $__LIST__ = $array;if( count($__LIST__)==0 ) : echo "" ;else: foreach($__LIST__ as $key=>$ta): $mod = ($i % 2 );++$i;?><tr id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO">
                    <td id="<?php echo ($ta['id']); ?>"><?php echo ($ta['sname']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-rep"><?php echo ($ta['rep']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-title"><?php echo ($ta['title']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-WAIT-content"><?php echo ($ta['content']); ?></td>
                    <td id="<?php echo ($ta['num']); ?>-<?php echo ($ta['years']); ?>-NO-reason"><?php echo ($ta['reason']); ?></td>  
                  </tr><?php endforeach; endif; else: echo "" ;endif; ?>
                </tbody>
                </table>

</div>

        
        
</div>
    
</body>
</html>