<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
    <style>
 input
      {
        outline: none;
      }
      select
        {

              outline: none;
        }
    </style>
    <script type="text/javascript">
       
    </script>
</head>
<body>
  <form  id="changeTa">

    <div style="margin-left: 20px;margin-right: 20px;margin-top: 20px;">
        <div><h>获奖名称</h></div>
        <div><input type="text" name="achName" id="name" style="width: 630px;height: 30px;" value=""></div>
    </div>
    <div style="margin-top: 20px;margin-left: 20px;margin-right: 20px;">
        <div><h>设奖部门</h></div>
        <div><input type="text" name="achDep"  id="dep" style="width: 630px;height: 30px;" value=""></div>
    </div>
    <div style="margin-left: 20px;margin-top: 20px;margin-right: 20px;">
        <div><h>获奖时间</h></div>
        <div><input type="date" name="achTime" id="tm" style="width: 200px;height: 30px;" value=""></div>
    </div>
    <div style="margin-left: 20px;margin-top: 20px;margin-right: 20px;">
        <div><h>奖励等级</h></div>
        <div><input type="text" name="achLv" id="lv" style="width: 200px;height: 30px;" value=""></div>
    </div>
    <div style="margin-left: 20px;margin-top: 20px;margin-right: 20px;">
        <div><h>佐证材料</h></div>
        <div><input type="file" name="achSup" ></div>
        <div><h style="color:#BC2F2E ">*若有多个文件需要上传，请打包或压缩包上传</h></div>
    </div>
    <div style="margin-left: 20px;margin-top: 20px;margin-right: 20px;">
        <input  type="submit" name="submit" id="updateOld" style="width: 166px;border:none;height: 30px;border-radius: 4px;background-color: rgba(188, 47, 46, 1);color: rgba(255, 255, 255, 1);font-size: 14px;text-align: center;" value="保存并提交审核">
    </div>
 </form>
</body>
</html>