<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

    <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <!-- 引入layui -->
    <script type="text/javascript" src="/mksys/Public/syspkg/layer/layer.js"></script>
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
     input
  {
   outline:none;
  }
    select
  {
    outline:none;
  }
        .home
        {
            
            width: 121px;
            height: 35px;
            line-height: 35px;
            color: rgba(16, 16, 16, 1);
            font-size: 24px;
            text-align: center;
            font-family: Roboto;

        }
         .teacher
        {
            position: relative;
            
            top: -25px;
            width: 424px;
            height: 0px;
            line-height: 19px;
            color: rgba(170, 170, 170, 1);
            font-size: 13px;
            text-align: center;
            font-family: Roboto;

        }
         body.my-skin.layui-layer-btn1{background-color: #BC2F2E;}
         body.my-skin.icon{color: red;}
    </style>
    <script type="text/javascript">
   $(document).ready(function(){

  var pageId = '<?php echo ($page); ?>';
       //页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：

if(pageId=='page8')
{
    
    $("#m5").css("background-color","#363536");
    $("#d5").css("display","inline");
}





$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'75px'
    },"fast")}else if(heit=="75px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
<script>
    $(document).ready(function(){

// 弹窗
 layer.config({
        skin:'my-skin'
    });


$("input.confirm").click(function(){
    var id = $(this).attr('id');
    layer.open({
  type: 2,
  skin: 'layui-layer-rim', //加上边框
  title:'管理密匙确认',
  area: ['290px', '310px'],//宽高
  content: 'superAdminKey.html',
  success: function(layero,index)
                    {
                      var button = layer.getChildFrame('input#btn',index);
                      button.click(function(){
                        var form = layer.getChildFrame('form#key',index);
                        
                        form.ajaxSubmit({
                          url : "<?php echo U('Admin/keyConfirm');?>",
                          type : "post",
                          dataType:'json',
                          success: function(data){
                            if(data == "success"){
                             if(id == 'btn1'){
                                $('form#tsecL').ajaxSubmit({
                                    url : "<?php echo U('Admin/updateTsecL');?>",
                                    type : "post",
                                    dataType : "json",
                                    success : function(data){
                                        if(data == "success"){
                                             layer.closeAll();
                                        alert("教学秘书账户修改成功");
                                        window.location.reload();
                                        }else if(data == "cookiefail"){
                                            layer.closeAll();
                                             window.location.href = "<?php echo U('Index/index');?>";
                                        }else if(data=="lengthfail"){
                                             layer.closeAll();
                                            alert('账户密码长度不对');
                                             window.location.reload();
                                        }
                                        else{
                                            layer.closeAll();
                                            alert('教学秘书账户修改失败');
                                             window.location.reload();
                                        }
                                       
                                    }
                                });
                             }
                             if(id == 'btn2'){                              
                                 $('form#SRsecL').ajaxSubmit({
                                    url : "<?php echo U('Admin/updateSRsecL');?>",                                
                                    type : "post",
                                    dataType : "json",
                                    success : function(data){
                                        if(data == "success"){
                                             layer.closeAll();
                                        alert("科研秘书账户修改成功");
                                        window.location.reload();
                                        }else if(data == "cookiefail"){
                                            layer.closeAll();
                                             window.location.href = "<?php echo U('Index/index');?>";
                                        }else if(data=="lengthfail"){
                                             layer.closeAll();
                                            alert('账户密码长度不对');
                                             window.location.reload();
                                        }
                                        else{
                                            layer.closeAll();
                                            alert('科研秘书账户修改失败');
                                             window.location.reload();
                                        }
                                    }
                                });

                             }
                             if(id == 'btn3'){

                                    $('form#SadminL').ajaxSubmit({
                                    url : "<?php echo U('Admin/updateSadminL');?>",
                                    type : "post",
                                    dataType : "json",
                                    success : function(data){
                                        if(data == "success"){
                                             layer.closeAll();
                                        alert("办公室主任账户修改成功");
                                        window.location.reload();
                                        }else if(data == "cookiefail"){
                                            layer.closeAll();
                                             window.location.href = "<?php echo U('Index/index');?>";
                                        }else if(data=="lengthfail"){
                                             layer.closeAll();
                                            alert('账户密码长度不对');
                                             window.location.reload();
                                        }
                                        else{
                                            layer.closeAll();
                                            alert('办公室主任账户修改失败');
                                             window.location.reload();
                                        }
                                    }
                                });
                             }
                         }else if(data == "cookiefail"){
                                window.location.href = "<?php echo U('Index/index');?>";
                            }else{
                                layer.closeAll();
                                alert('管理密匙验证失败！');
                                window.location.reload();
                            }
                           
                         }
                        });
                        
                      });
                    
                    }
});

});

    });
 $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'C1_B5' || auth == 'C2_B5'){
            $("li.userpd").hide();
            $("li.adminpd").hide();
             if(auth == 'C1_B5'){
                $("h#auth").text("教学秘书");
            }else{
                $("h#auth").text("科研秘书");
            }
        }else{
            $("h#auth").text("超级管理员");
        }
        });
 /*退出登录*/
        $(document).ready(function(){
             $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });
        });

</script>
</head>

<body class="body">
<!-- 头部 -->
    <header>

    <!-- 头顶状态栏 -->
        <div class="head">

            <div  class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold; ">
                <h id="auth"></h>
                    <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom "style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

            </div>
        </div>
    </header>
    <div id="ddm" style="position: fixed;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
        <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
            <li  style=";padding-left: 10px;padding-top: 10px;"><a id="quit" style="color: black;">退出</a></li>
        </ul>
    </div>
     <!-- 导航栏 -->
   
   <nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top: 68px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 108px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 148px;background-color:#BC2F2E;display: none;"></div>
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 438px;background-color:#BC2F2E;display: none;"></div>

         <li style="" id="drp1"><a style="cursor:pointer">查看院内</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style=""id="dm11"><a href="<?php echo U('Admin/superAdmin');?>">院内统计信息</a></li>
            <li style=""id="dm12"><a href="<?php echo U('Admin/superAdminClassifySearch');?>">按分类查看</a></li>
            <li style=""id="dm13"><a href="<?php echo U('Admin/superAdminUserFind');?>">按教师查看</a></li>
            </ul>
        <li style="" id="drp2"><a style="cursor:pointer">教学审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style=""id="dm21"><a href="<?php echo U('Admin/superAdminTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Admin/superAdminTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a href="<?php echo U('Admin/superAdminTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研审核</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Admin/superAdminResearchPap');?>">论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Admin/superAdminResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Admin/superAdminResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Admin/superAdminResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Admin/superAdminResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m1"><a href="<?php echo U('Admin/superAdminOtherExc');?>">国际交流</a></li>
        <li id="m2"><a href="<?php echo U('Admin/superAdminOtherWel');?>">公益活动</a></li>
        <li id="m3"><a href="<?php echo U('Admin/superAdminOtherNews');?>">新闻记录</a></li>
      <li id="m4" class="userpd"><a href="<?php echo U('Admin/superAdminUserPd');?>">账号管理</a></li>
        <li id="m5" class="adminpd"><a href="<?php echo U('Admin/superAdminAdminPd');?>">管理员账号</a></li>
        </ul>
    </nav>
<div class="main" id="maine" style="padding-left: 50px;padding-top: 50px;">

<div class="home">
            <h style="font-weight: bold;">管理员账号</h>
        </div>
        <div class="hr0">
            <hr>
        </div>

   <div style="font-size: 14px;font-family: Roboto;">

   <div><h>教学秘书</h></div>
    <form id="tsecL">
    <div style="margin-top: 15px;">
   <div style="width: 150px;float: left;"><h>账号</h>
   <input type="text" id="tsecL" name="TsecId" value="<?php echo ($adminInf[0]['id']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);"></div>

   <div style="width: 150px;float: left;"><h>密码</h>
   <input type="text" name="TsecPd"   value="<?php echo ($adminInf[0]['pd']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);" /></div>
   </div>
   <div><input id="btn1"  class="confirm" type="button" name="submit" style="width: 100px;border:none;height: 30px;border-radius: 4px;background-color: rgba(188, 47, 46, 1);color: rgba(255, 255, 255, 1);font-size: 14px;text-align: center;margin-top: 20px;" value="保存设置" />
   </div>
   </form>
   </div>

   


   <div style="font-size: 14px;font-family: Roboto;margin-top: 50px;">

   <div><h>科研秘书</h></div>
   <form id="SRsecL">
    <div style="margin-top: 15px;">
   <div style="width: 150px;float: left;"><h>账号</h>
   <input type="text" id="SRsecL" name="SRsecId"  value="<?php echo ($adminInf[1]['id']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);"></div>

   <div style="width: 150px;float: left;"><h>密码</h>
   <input type="text" name="SRsecPd" value="<?php echo ($adminInf[1]['pd']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);"></div>
   </div>
   <div><input id="btn2" class="confirm" type="button" name="submit" style="width: 100px;border:none;height: 30px;border-radius: 4px;background-color: rgba(188, 47, 46, 1);color: rgba(255, 255, 255, 1);font-size: 14px;text-align: center;margin-top: 20px;" value="保存设置" >
   </div>
   </form>
   </div>



   <div style="font-size: 14px;font-family: Roboto;margin-top: 50px;">

   <div><h>办公室主任（超管）</h></div>
   <form id="SadminL">
    <div style="margin-top: 15px;">
   <div style="width: 150px;float: left;"><h>账号</h>
   <input type="text" id="SadminL" name="SadminId" value="<?php echo ($adminInf[2]['id']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);" class="bt"></div>

   <div style="width: 150px;float: left;"><h>密码</h>
   <input type="text" name="SadminPd" value="<?php echo ($adminInf[2]['pd']); ?>" style="width: 87px;height: 30px;color: rgba(0, 0, 0, 1);font-size: 14px;text-align: left;font-family: Roboto;border: 1px solid rgba(0, 0, 0, 1);" class="bt" ></div>
   </div>
   <div><input id="btn3" class="confirm" type="button" name="submit" style="width: 100px;border:none;height: 30px;border-radius: 4px;background-color: rgba(188, 47, 46, 1);color: rgba(255, 255, 255, 1);font-size: 14px;text-align: center;margin-top: 20px;" value="保存设置" class="bt">
   </div>
   </form>
   </div>

</div>
    
</body>
</html>