<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--导入jQuery-->
     <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <title>教师成果网-重置密码</title>
    <style>
     input
      {
        outline: none;
      }
      select
        {
                     outline: none;
        }
        html
        {
            width: 100%;
            height: 100%;
        }
        body
        {

            width: 100%;
            height: 100%;

        }
        .head
        {
            position: relative;
            width: 100%;
            height: 13%;
            line-height: 52px;
            background-color: #962C2C;
            color: rgba(255, 255, 255, 1);
            font-size: 36px;
            text-align: left;
            font-family: Roboto;

        }
        .bd
        {   position: relative;
            width: 100%;
            height: 74%;
            background-image:url("/mksys/Public/syspkg/images/back.jpg") ;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;

        }
        footer
        {
            background-color: #962C2C;
            width: 100%;
            height: 13%;
        }
        .main
        {

            position: relative;

            right:-60% ;
            top: 190px;
            width: 444px;
            height: 389px;
            line-height: 20px;
            border-radius: 20px;
            background-color: rgba(54, 53, 54, 1);
            text-align: center;


        }
        .login
        {
            position: relative;
            left:-42px;
            top:37px;
            width: 400px;
            height: 41px;
            line-height: 41px;
            color: rgba(255, 255, 255, 1);
            font-size: 26px;
            text-align: center;
            font-family: Roboto;

        }
        .id
        {
            position: relative;
            top: 55px;
            padding-left: 10px;
            width: 279px;
            height: 50px;
            border-radius: 10px;
            color: rgba(136, 136, 136, 1);
            font-size: 14px;
            text-align: left;
            font-family: Roboto;
            border: 1px solid rgba(187, 187, 187, 1);

        }
        .name
        {
            position: relative;
            padding-left: 10px;
            top: 75px;
            width: 279px;
            height: 50px;
            border-radius: 10px;
            color: rgba(136, 136, 136, 1);
            font-size: 14px;
            text-align: left;
            font-family: Roboto;
            border: 1px solid rgba(187, 187, 187, 1);

        }
        .id6
        {
            position: relative;
            padding-left: 10px;
            left: 70px;
            top: 95px;
            width: 279px;
            height: 50px;
            border-radius: 10px;
            color: rgba(136, 136, 136, 1);
            font-size: 14px;
            text-align: left;
            font-family: Roboto;
            border: 1px solid rgba(187, 187, 187, 1);

        }
        .submit
        {
            position: relative;
            left: -210px;
            top: 180px;
            width: 130px;
            height: 49px;
            border-radius: 10px;
            background-color: rgba(188, 47, 46, 1);
            color: rgba(255, 255, 255, 1);
            font-size: 18px;
            text-align: center;
            font-family: Microsoft Yahei;

        }
        .cancel
        {
            position: relative;
            left: 78px;
            top: 129px;
            width: 130px;
            height: 49px;
            border-radius: 10px;
            background-color: rgba(255, 255, 255, 1);
            color: rgba(188, 47, 46, 1);
            font-size: 18px;
            text-align: center;
            font-family: Microsoft Yahei;
            border: 1px solid rgba(188, 47, 46, 1);

        }
        .tips
        {
            position: relative;
            left: 81px;
            top: 50px;
            width: 274px;
            height: 23px;
            line-height: 19px;
            color: rgba(255, 255, 255, 1);
            font-size: 13px;
            text-align: center;
            font-family: Roboto;

        }

    </style>
</head>
<script>
    function form_confirm()
    {
        var id=document.getElementById("iid").value
        var psd=document.getElementById("psd").value
        if (id.length!=10)
        {
            alert("工号长度有误");
            return false;
        }
        var reg = /^[0-9]+$/;
        if(id!=""&&!reg.test(id)){
            alert("账号只能输入数字！");
            return false;
        }
        var zmnumReg=/^[0-9a-zA-Z]*$/;
        if(psd!=""&&!zmnumReg.test(psd)){
            alert("密码只能输入是字母或者数字,请重新输入");
            return false; }
        if(psd.length!=6)
        {
            alert("密码长度有误");
            return false;
        }
    }
</script>
<body class="bodyy" >
<!-- 头部 -->
<header class="head">
    <div  style="float: left;margin-top: 30px;"><img src="/mksys/Public/syspkg/images/tip.png" style="height: 60px;width: 60px;margin-left: 10px;"><img src="/mksys/Public/syspkg/images/name.png" style="width: 249px;height: 51px;margin-left: 20px;"></div>
    <div style="float: left;margin-left: 36px;"><h style="height: 120px; line-height: 120px;"> 马克思主义学院</h></div>
</header>
<!-- 主体 -->
<div class="bd">
    <div class="main">
        <div class="login">
            <img style="height: 40px;width: 40px;" src="/mksys/Public/syspkg/images/app.png" >&nbsp;&nbsp;重置密码
        </div>

        <form onsubmit="return form_confirm()" action="<?php echo U('index/changePd');?>"  method="POST">
            <fieldset>
                <!-- id框 -->
                <input id="id" type="text" name="id" class="id"  placeholder="请输入工号">
                <!-- 姓名框 -->
                <input id="name" type="text" name="name" class="name" placeholder="请输入姓名">
                <!-- 身份证后六位框 -->
                <input id="psd" type="text" name="idnum" class="id6" placeholder="请输入身份证后六位">
                <!-- 提交 -->
                <input type="submit" name="submit" class="submit" value="提交">
                <!-- 取消 -->
                <button type="button" name="cancel" class="cancel" href="<?php echo U('Index/index');?>"><a href="<?php echo U('Index/index');?>" >取消</a></button>
                <!--tips  -->
                <div class="tips">
                    <h name="tips"></h>
                </div>
            </fieldset>

        </form>


    </div>
</div>
<footer >
    <div style="width: 400px;height: 26px;line-height: 26px;color: rgba(255, 255, 255, 1);font-size: 18px;font-family: Roboto;left: 1%;top: 70%;position: relative;">
        <h > Copyright © 2018 NWPU. All Rights Reserved.</h></div>
</footer>
</body>
</html>