<?php if (!defined('THINK_PATH')) exit();?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description"content="Basic HTML5 App generated by MyEclipse Mobile Tools" />

    <!--引入jquery-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-3.2.1.min.js"></script>
      <!--导入jQueryForm插件-->
    <script type="text/javascript" src="/mksys/Public/syspkg/jquery-form.js"></script>
    <!--引入Bootstrap-->
    <link href="/mksys/Public/syspkg/bootstrap3.3.7/css/bootstrap.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/bootstrap3.3.7/js/bootstrap.js"></script>
    <!-- 引入layui -->
    <script type="text/javascript" src="/mksys/Public/syspkg/layer/layer.js"></script>
    <!-- <link rel="stylesheet" type="text/css" href="/mksys/Public/syspkg/css/jiaoxue.css"> -->
    <link href="/mksys/Public/syspkg/css/fram.css" rel="stylesheet" >
    <script type="text/javascript" src="/mksys/Public/syspkg/js/fram.js"></script>
    <title>教师成果网-普通教师端</title>
    <style>
     input
      {
        outline: none;
      }
      select
        {
            width: 91px;
            height: 30px;
             border-radius: 10px;
              outline: none;
        }
         .home
        {
            
            width:120px;
            height: 35px;
            line-height: 35px;
            color: rgba(16, 16, 16, 1);
            font-size: 24px; 
            text-align: center;
            font-family: Roboto;

        }

        .hr0
        {
           position: relative;
            top: -10px;
           width: 100%
            height: 12px;

        }
        table
        {
            margin-top: 20px;
            border: solid;
            border-radius: 10px;
            background-color: rgba(255, 255, 255, 1);
            text-align: center;
            border-collapse: separate;
            border: 2px solid #A6A6A6 ;
            padding-left: 
        }
        td
        {
            width: 200px;
            height: 45px;

        }
        thead td
        {
            border-bottom: 1px solid #A6A6A6 ;
        }
        thead td.tdHead
        {
            font-size: 20px;
            font-weight: bold;
        }
        tbody td.tdHead
        {
            font-size: 16px;
            font-weight: bold;
        }
        .tdRest
        {

        }
    </style>
<script>
       /*自动检测*/
    $(document).ready(function(){
        // 自动检测年份
        var years = '<?php echo ($years); ?>';
        if(years == '时间不限'){
            $("option#years-all").attr("selected","selected");
        }else if(years == '2017'){
             $("option#years-2017").attr("selected","selected");
        }else if(years == '2018'){
            $("option#years-2018").attr("selected","selected");
        }  

    });
      $(document).ready(function(){
        // 权限检测
        var auth = '<?php echo (cookie('login_auth')); ?>';
        if(auth == 'B1_A'){
            $("li.see").hide();
            $("ul.see").hide();
        }

           /*退出登录*/
        $("a#quit").click(function(){
          $.post("<?php echo U('Index/quit');?>",
            function(){
              $(location).prop('href',"<?php echo U('Index/index');?>");
            }
            );
        });
    });

    $(document).ready(function(){
        $("select#years").change(function(){
            $("input#submit").click();
        });
    });
</script>
</head>

<body class="body">
<!-- 头部 -->
    <header>

    <!-- 头顶状态栏 -->
        <div class="head">

            <div  id="hd" class="nameOfTeacher" style="border: solid;border-radius: 10px;background-color: white;font-weight: bold;height: 30px; ">
                <h ><?php echo (cookie('user_name')); ?></h>
                    <span  id="dd" class="iconBlack glyphicon glyphicon-triangle-bottom "style=" float: right;height:20px;width:20px;border: none;background-color: white;margin-right: 10px;margin-top: 3px;" ></span>

            </div>
        </div>
    </header>
    <div id="ddm" style="position: fixed;right: 5px;top: 72px;width: 100px;display:none; z-index: 1;">
        <ul  style="list-style-type: none;padding-left: 0px;padding-top: 0px;">
            <li style="padding-left: 10px;padding-top: 10px;"><a href="<?php echo U('Home/generalTeacherUserInf');?>" style="color: black;" >个人信息</a></li>
            <li  style=";padding-left: 10px;padding-top: 10px;"><a id="quit" href="" style="color: black;">退出</a></li>
        </ul>
    </div>
    <!-- 导航栏 -->
   <script type="text/javascript">

   $(document).ready(function(){

var pageId = '<?php echo ($page); ?>';
//页面编码为： page1 
 //            page21 page22 page23
 //            page31 page32 page33 page34 page35
 //            ......
//switch case 实例：

if(pageId=='page1')
{
    $("#m1").css("background-color","#363536");
    $("#d1").css("display","inline");
}

$("#dd").click(function(){
    var heit = $("div.nameOfTeacher").css("height");
    
    if(heit=="30px"){
    $("div.nameOfTeacher").animate(
    {
        height:'100px'
    },"fast")}else if(heit=="100px"){
    $("div.nameOfTeacher").animate(
    {
        height:'30px'
    },"fast")}
})

    })</script>
    <nav class="nave" style="">
        <ul style="list-style-type: none;line-height: 60px;margin-left: -40px; ">
<div id="d21" style="position:absolute;height:25px;width: 8px;left: -2px;top: 128px;background-color:#BC2F2E;display: none;"></div>
<div id="d22" style="position:absolute;height:25px;width: 8px;left: -2px;top: 168px;background-color:#BC2F2E;display: none;"></div>
<div id="d23" style="position:absolute;height:25px;width: 8px;left: -2px;top: 208px;background-color:#BC2F2E;display: none;"></div>
<div id="d31" style="position:absolute;height:25px;width: 8px;left: -2px;top: 188px;background-color:#BC2F2E;display: none;"></div>
<div id="d32" style="position:absolute;height:25px;width: 8px;left: -2px;top: 228px;background-color:#BC2F2E;display: none;"></div>
<div id="d33" style="position:absolute;height:25px;width: 8px;left: -2px;top: 268px;background-color:#BC2F2E;display: none;"></div>
<div id="d34" style="position:absolute;height:25px;width: 8px;left: -2px;top: 308px;background-color:#BC2F2E;display: none;"></div>
<div id="d35" style="position:absolute;height:25px;width: 8px;left: -2px;top: 348px;background-color:#BC2F2E;display: none;"></div>
<div id="d1" style="position:absolute;height:25px;width: 8px;left: -2px;top: 18px;background-color:#BC2F2E;display: none;"></div>
<div id="d2" style="position:absolute;height:25px;width: 8px;left: -2px;top: 198px;background-color:#BC2F2E;display: none;"></div>
<div id="d3" style="position:absolute;height:25px;width: 8px;left: -2px;top: 258px;background-color:#BC2F2E;display: none;"></div>
<div id="d4" style="position:absolute;height:25px;width: 8px;left: -2px;top: 318px;background-color:#BC2F2E;display: none;"></div>
<div id="d5" style="position:absolute;height:25px;width: 8px;left: -2px;top: 378px;background-color:#BC2F2E;display: none;"></div>
<div id="d11" style="position: absolute;height:25px;width: 8px;left: -2px;top:488px;background-color:#BC2F2E;display: none;"></div>
<div id="d12" style="position:absolute;height:25px;width: 8px;left: -2px;top: 528px;background-color:#BC2F2E;display: none;"></div>
<div id="d13" style="position:absolute;height:25px;width: 8px;left: -2px;top: 568px;background-color:#BC2F2E;display: none;"></div>

        <li id="m1"><a href="<?php echo U('Home/generalTeacher');?>">首页</a></li>
        <li style="" id="drp2"><a style="cursor:pointer">教学情况</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none; font-size: 16px; "id="drpmanu2" >
            <li style="" id="dm21"><a href="<?php echo U('Home/generalTeacherTeachAch');?>">教学成果奖</a></li>
            <li style=""id="dm22"><a href="<?php echo U('Home/generalTeacherTeachPro');?>">教改立项/精品课程</a></li>
            <li style=""id="dm23"><a  href="<?php echo U('Home/generalTeacherTeachTbp');?>">教材出版</a></li>
            </ul>
        <li style="" id="drp3"><a style="cursor:pointer">科研情况</a></li>
            <ul style=" list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px; "id="drpmanu3" >     <li style=""id="dm31"><a href="<?php echo U('Home/generalTeacherResearchPap');?>" >论文发表</a></li>
            <li style=""id="dm32"><a href="<?php echo U('Home/generalTeacherResearchMpb');?>">学术专著/译著出版</a></li>
            <li style=""id="dm33"><a href="<?php echo U('Home/generalTeacherResearchAch');?>">科研成果奖</a></li>
            <li style=""id="dm34"><a href="<?php echo U('Home/generalTeacherResearchPro');?>">科研项目主持</a></li>
            <li style=""id="dm35"><a href="<?php echo U('Home/generalTeacherResearchFund');?>">基金类</a></li>
            </ul>
        <li id="m2"><a href="<?php echo U('Home/generalTeacherOtherExc');?>">国际交流</a></li>
        <li id="m3"><a href="<?php echo U('Home/generalTeacherOtherWel');?>">公益活动</a></li>
        <li id="m4"><a href="<?php echo U('Home/generalTeacherOtherNews');?>">新闻记录</a></li>
        <li id="m5"><a href="<?php echo U('Home/generalTeacherUserInf');?>">账号管理</a></li>
         <li style="" class="see" id="drp1"><a>查看院内</a></li>
           <ul class="see" style="list-style-type: none;line-height: 40px;margin-left: -40px;display:none;font-size: 16px;"id="drpmanu1" >     <li style="" id="dm11"><a href="<?php echo U('Home/generalTeacherCount');?>">院内统计信息</a></li>
            <li style="" id="dm12"><a href="<?php echo U('Home/generalTeacherClassifySearch');?>">按分类查看</a></li>
            <li style="" id="dm13"><a href="<?php echo U('Home/generalTeacherUserFind');?>">按教师查看</a></li>
           
            </ul>
        </ul>
    </nav>
    
<div class="main" style="">

<div class="home">
            <h style="font-weight: bold;"><?php echo (cookie('user_name')); ?></h>
        </div>
<div style="position: absolute;left: 200px;top: 60px;color: #AAAAAA;width: 820px;">
            系别:<h name="xi"><?php echo ($inf["job"]["dep"]); ?> </h>  
            工号:<h name="ide"><?php echo ($inf["info"]["id"]); ?></h>     
            职务:<h name="duty"> <?php echo ($inf["job"]["pos"]); ?></h>   
            职称:<h name="job"> <?php echo ($inf["job"]["title"]); ?></h>          
            岗位级别:<h name="level"><?php echo ($inf["job"]["lv"]); ?></h>   
        </div>
        
 <hr>           
             <form action="<?php echo U('Home/generalTeacher');?>" method="POST">
                <select id="years" name="years">
                       <option id="years-all" value="不限">时间不限</option>
                        <option id="years-2017" value="2017">2017</option>
                        <option id="years-2018" value="2018">2018</option>
                </select>
                <input type="submit" id="submit" name="submit" style="display: none;">
            </form>
<!-- 教学 -->
<table>
    <thead >
    <tr >
        <td class="tdHead">教学情况</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['teachAllYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['teachAllWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['teachAllNO']); ?></strong>项</td>
                    <td class="tdRest" style="width: 50px;"><a><span class="glyphicon glyphicon-save" ></span></a></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tdHead">教学成果奖</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['teachAchYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['teachAchWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['teachAchNO']); ?></strong>项</td>
    </tr>
    <tr>
        <td class="tdHead">教改立项/精品课程类</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['teachProYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['teachProWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['teachProNO']); ?></strong>项</td>
    </tr>
    <tr>
        <td class="tdHead"style="padding-left: 3px;">教材出版</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['teachTbpYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['teachTbpWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['teachTbpNO']); ?></strong>项</td>
    </tr>
    </tbody>
</table>
<!-- 科研 -->
<table>
    <thead>
    <tr>
       <td class="tdHead">科研情况</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchAllYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchAllWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchAllNO']); ?></strong>项</td>
                     <td class="tdRest" style="width: 50px;"><a><span class="glyphicon glyphicon-save" ></span></a></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tdHead">论文发表</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchPapYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchPapWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchPapNO']); ?></strong>项</td>
    </tr>
    <tr>
        <td class="tdHead">学术专著/译著出版</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchMpbYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchMpbWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchMpbNO']); ?></strong>项</td>
    </tr>
    <tr>
       <td class="tdHead">科研成果奖</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchAchYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchAchWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchAchNO']); ?></strong>项</td>
    </tr>
    <tr>
       <td class="tdHead">科研项目主持</td>
                   <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchProYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchProWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchProNO']); ?></strong>项</td>
    </tr>
    <tr>
        <td class="tdHead">基金类</td>
                   <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['researchFundYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['researchFundWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['researchFundNO']); ?></strong>项</td>
    </tr>
    </tbody>
</table>
<!-- 其他 -->
<table>
    <thead>
    <tr>
        <td class="tdHead">其他情况</td>
                  <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['otherAllYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['otherAllWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['otherAllNO']); ?></strong>项</td>
                     <td class="tdRest" style="width: 50px;"><a><span class="glyphicon glyphicon-save" ></span></a></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="tdHead">国际交流</td>
                    <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['otherExcYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['otherExcWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['otherExcNO']); ?></strong>项</td>
    </tr>
    <tr>
        <td class="tdHead">公益活动</td>
                     <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['otherWelYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['otherWelWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['otherWelNO']); ?></strong>项</td>
    </tr>
    <tr>
         <td class="tdHead">新闻记录</td>
                <td class="tdRest">已通过<strong style="color:red"><?php echo ($all['otherNewsYES']); ?></strong>项</td>
                    <td class="tdRest">待通过<strong style="color:blue"><?php echo ($all['otherNewsWAIT']); ?></strong>项</td>
                    <td class="tdRest">未通过<strong style="color:purple"><?php echo ($all['otherNewsNO']); ?></strong>项</td>
    </tr>
    </tbody>
</table>
</div>
    
</body>
</html>